server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pp_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none)
    show-sql: true      # SQL SHOW
    properties:
      hibernate:
        format_sql: true # SQL
  mail:
    host: smtp.gmail.com              # SMTP HOST
    port: 587                         # SMTP PORT (587 or 465)
    username: moter2588@gmail.com
    password: ndzz ejdw klvw owsg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        auth-code-expiration-millis: 5 * 60 * 1000
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
          must-revalidate: true
          no-cache: true
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      duration: 600

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#jwt
jwt:
  secret: ZG6xp0zX8Pd4M9gXXtKQRTpJfhtJk2QFpHTZbwMcv6g=
  accessExpiredTime: 300000 # 5 min
  refreshExpiredTime: 86400000 # 1 day

# logging
logging:
  level:
    org.hibernate.SQL: debug         # Hibernate SQL
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security.web.authentication: debug