server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pp_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none)
    show-sql: true      # SQL SHOW
    properties:
      hibernate:
        format_sql: true # SQL
  mail:
    host: smtp.gmail.com              # SMTP HOST
    port: 587                         # SMTP PORT (587 or 465)
    username: happy@likelion.org
    password: kjji ostv tkop jpgx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# logging
logging:
  level:
    org.hibernate.SQL: debug         # Hibernate SQL
    org.hibernate.type.descriptor.sql.BasicBinder: trace